openapi: 3.0.0
info:
  title: Crypto Trading Educational Platform API
  description: API for managing trading strategies, backtesting, and user portfolios.
  version: 1.0.0
servers:
  - url: /api
paths:
  /health:
    get:
      summary: Health Check
      description: Returns the health status of the backend server.
      responses:
        '200':
          description: A healthy response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
  /auth/register:
    post:
      summary: Register a new user
      description: Creates a new user account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '201':
          description: User created successfully.
  /auth/login:
    post:
      summary: Login a user
      description: Authenticates a user and returns a JWT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Successful login.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /strategies:
    get:
      summary: Get available strategies
      description: Returns a list of all available trading strategies.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of strategies.
        '401':
          description: Unauthorized.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
