name: agent-tick
on:
  schedule:
    - cron: "*/10    *"
  workflow_dispatch:
permissions:
  contents: write
  issues: write
jobs:
  run-agent:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Prepare environment
        run: |
          chmod +x ./start.sh
          echo "TICKAT=$(date -u +%FT%TZ)" >> $GITHUB_ENV
          if ! command -v jq >/dev/null; then sudo apt-get update && sudo apt-get install -y jq; fi

      - name: Restore state
        id: state
        run: |
          if [ ! -f .agent_state.json ]; then
            echo '{"last_run": null, "failures": 0}' > .agent_state.json
          fi
          echo "state=$(cat .agent_state.json | tr -d '\n' | sed 's/\"/\\\"/g')" >> $GITHUB_OUTPUT

      - name: Run agent tick
        id: tick
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AGENTSTATEJSON: "${{ steps.state.outputs.state }}"
        run: |
          set -e
          ./start.sh

      - name: Update state on success
        if: success()
        run: |
          jq --arg now "$(date -u +%FT%TZ)" '.last_run=$now | .failures=0' .agent_state.json > .agent_state.json.new
          mv .agent_state.json.new .agent_state.json

      - name: Update state on failure
        if: failure()
        run: |
          jq '.failures=(.failures//0)+1' .agent_state.json > .agent_state.json.new
          mv .agent_state.json.new .agent_state.json

      - name: Commit state
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .agent_state.json
          if ! git diff --staged --quiet; then
            git commit -m "agent: update state at $TICKAT"
            git push
          else
            echo "No state changes to commit."
          fi

      - name: Escalate if repeated failures
        if: failure()
        env:
          GHTOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FAILS=$(jq -r '.failures' .agent_state.json 2>/dev/null || echo 0)
          if [ "$FAILS" -ge 3 ]; then
            TITLE="Agent failing ($FAILS) - $(date -u +%FT%TZ)"
            BODY="Agent failed $FAILS consecutive runs. Check Actions logs. Auto-pausing until review."
            echo "::notice::$TITLE"
            gh issue create --title "$TITLE" --body "$BODY" || true
          fi
