name: Agent

on:
  workflow_dispatch:        # تشغيل يدوي
  schedule:
    - cron: '*/10 * * * *'  # كل 10 دقائق (UTC)

permissions:
  contents: read

concurrency:
  group: agent-loop         # يمنع التداخل
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 12     # لا تتركه يعلق للأبد
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps (tolerant)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run bot and capture logs
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p artifacts
          python advanced_airdrop_automation.py 2>&1 | tee artifacts/run.log

      - name: Job summary
        if: always()
        run: |
          echo "### Agent run: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- Event: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Logs: artifact **agent-logs-${{ github.run_id }}**" >> $GITHUB_STEP_SUMMARY

      - name: Upload logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: agent-logs-${{ github.run_id }}
          path: artifacts/**
          retention-days: 7
